export const _onSuccess = action => action + '_SUCCESS';
export const _onFail = action => action + '_FAIL';
export const _onUnmount = action => action + '_UNMOUNT';

export default {
  //user
  TOKEN_USER: 'TOKEN_USER',
  GET_TOKEN: 'GET_TOKEN',
  GET_USER: 'GET_USER',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  LOG_OUT_USER: 'LOG_OUT_USER',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_PASSWORD: 'UPDATE_PASSWORD',
  //general
  GET_BIRTHDAY: 'GET_BIRTHDAY',
  GET_PARTNER: 'GET_PARTNER',
  GET_MEMBER: 'GET_MEMBER',
  GET_CONFIG: 'GET_CONFIG',
  GET_TERMS_OF_USE: 'GET_TERMS_OF_USE',
  GET_BANNER_BY_ID_HOME: 'GET_BANNER_BY_ID_HOME',
  GET_BANNER_BY_ID_SHOPPING: 'GET_BANNER_BY_ID_SHOPPING',
  //product
  SEARCH_SCREEN: 'SEARCH_SCREEN',
  GET_SEARCH_SUGGESTIONS: 'GET_SEARCH_SUGGESTIONS',
  GET_PRODUCT_GROUP_HOME: 'GET_PRODUCT_GROUP_HOME',
  GET_PRODUCT_IS_FOCUS: 'GET_PRODUCT_IS_FOCUS',
  GET_SHOPPING: 'GET_SHOPPING',
};
