export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  //root auth
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  //root bottom
  HOME_SCREEN: 'HOME_SCREEN',
  SHOPPING_SCREEN: 'SHOPPING_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
  VOUCHER_SCREEN: 'VOUCHER_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  //root common
  GET_START_SCREEN: 'GET_START_SCREEN',
  EDIT_USER_SCREEN: 'EDIT_USER_SCREEN',
  GET_SEARCH_SCREEN: 'GET_SEARCH_SCREEN',
  GET_BIRTHDAY_SCREEN: 'GET_BIRTHDAY_SCREEN',
  GET_PARTNER_SCREEN: 'GET_PARTNER_SCREEN',
  GET_MEMBER_SCREEN: 'GET_MEMBER_SCREEN',
  GET_MEMBER_DERAILS: 'GET_MEMBER_DERAILS',
  GET_PRODUCT_DETAILS: 'GET_PRODUCT_DETAILS',
  INFORMATION_DETAILS: 'INFORMATION_DETAILS',
};
