export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  //root auth
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  //root bottom
  HOME_SCREEN: 'HOME_SCREEN',
  SHOPPING_SCREEN: 'SHOPPING_SCREEN',
  QR_CODE_SCREEN: 'QR_CODE_SCREEN',
  VOUCHER_SCREEN: 'VOUCHER_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
